version: '3.8'

services:
  frontend:
    build:
      context: ./social-network-front
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Пробрасываем порт 80 контейнера на порт 4200 хоста
    depends_on:
      - backend

  backend:
    build:
      context: ./SocialNetworkBack
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Пробрасываем порт 80 контейнера на порт 5000 хоста
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
