version: '3.8'

services:
  frontend:
    build:
      context: ./social-network-front
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Доступ к фронтенду на порту 4200

  backend:
    build:
      context: ./SocialNetworkBack
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Доступ к бекенду на порту 5000
