# Укажите базовый образ
FROM node:18 AS build

# Установите рабочую директорию
WORKDIR /app

# Скопируйте package.json и package-lock.json
COPY package*.json ./

# Установите зависимости
RUN npm install

# Скопируйте все файлы в контейнер
COPY . .

# Соберите проект
RUN npm run build --prod

# Используйте легкий сервер для обслуживания приложения
FROM nginx:alpine

# Копируем собранные файлы в nginx
COPY --from=build /app/dist/social-network-front /usr/share/nginx/html

# Экспонируем порт 80
EXPOSE 80

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
